### ISSUE TITLE
Cambios en la API de Vistos Recientemente

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Web#31]
- sacar el endpoint delete /visto-recientemente (la lógica va a estar en el backend a la hora de agregar uno nuevo)
- pasar a utilizar solo dtos para la comunicación entre mobile y api (quitar todo lo relacionado a entities)
- convertir de dto a entity dentro de los dao (hacer el getConverter.toEntity dentro de cada DaoImpl probablemente así cada método sigue recibiendo un dto)

**Comment by ChortJulio** [comment]
Acabo de crear la rama '31-cambios-en-la-api-de-vistos-recientemente' para solucionar los 3 items en 3 commits separados (probablemente). Si puedo voy a relacionar el PR a este mismo issue también.
